// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vzpyamvunnhlzypzdbpf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ6cHlhbXZ1bm5obHp5cHpkYnBmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3ODQ0MzIsImV4cCI6MjA2OTM2MDQzMn0.UaU6mywmh6_3szVV3CwPc3Q7aiyRxSeY8Ivb_yBryB0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});